### ISSUE TITLE
Testes e2e retornando Error: getaddrinfo EAI_AGAIN mysql.newschoolapp.com.br

### ISSUE THREAD

**Issue by felinto-dev** [NewSchoolApp/newschool-backend#634]
Não estou conseguindo rodar os testes e2e. Apenas executei "npm run test:e2e" depois de clonar o projeto e copiar o arquivo .env.example para .env

Existe alguma configuração adicional que precisa ser feita?

```
emers@DESKTOP-VKD8FTV MINGW64 ~/Documents/newschool-backend (master)
$ yarn test:e2e
yarn run v1.22.5
$ jest --config ./test/jest-e2e.config.js --runInBand
[Nest] 8956   - 10/02/2021 05:44:21   [ExceptionHandler] Unable to connect to the database. Retrying (1)...
Error: connect ETIMEDOUT
    at PoolConnection.Object.<anonymous>.Connection._handleConnectTimeout (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:409:13)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol.Object.<anonymous>.Protocol._enqueue (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.Object.<anonymous>.Pool.getConnection (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.Object.<anonymous>.MysqlDriver.createPool (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:344:36)
    at step (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:122:57)
[Nest] 8956   - 10/02/2021 05:44:34   [ExceptionHandler] Unable to connect to the database. Retrying (2)... +13032ms
Error: connect ETIMEDOUT
    at PoolConnection.Object.<anonymous>.Connection._handleConnectTimeout (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:409:13)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol.Object.<anonymous>.Protocol._enqueue (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.Object.<anonymous>.Pool.getConnection (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.Object.<anonymous>.MysqlDriver.createPool (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:344:36)
    at step (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:122:57)
[Nest] 8956   - 10/02/2021 05:44:37   [ExceptionHandler] Unable to connect to the database. Retrying (3)... +3008ms
Error: getaddrinfo EAI_AGAIN mysql.newschoolapp.com.br
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    --------------------
    at Protocol.Object.<anonymous>.Protocol._enqueue (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.Object.<anonymous>.Pool.getConnection (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.Object.<anonymous>.MysqlDriver.createPool (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:344:36)
    at step (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:122:57)
[Nest] 8956   - 10/02/2021 05:44:50   [ExceptionHandler] Unable to connect to the database. Retrying (4)... +13017ms
Error: connect ETIMEDOUT
    at PoolConnection.Object.<anonymous>.Connection._handleConnectTimeout (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:409:13)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol.Object.<anonymous>.Protocol._enqueue (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.Object.<anonymous>.Pool.getConnection (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.Object.<anonymous>.MysqlDriver.createPool (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:344:36)
    at step (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:122:57)
[Nest] 8956   - 10/02/2021 05:44:53   [ExceptionHandler] Unable to connect to the database. Retrying (5)... +3018ms
Error: getaddrinfo EAI_AGAIN mysql.newschoolapp.com.br
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    --------------------
    at Protocol.Object.<anonymous>.Protocol._enqueue (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.Object.<anonymous>.Pool.getConnection (C:\Users\emers\Documents\newschool-backend\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:894:18
    at new Promise (<anonymous>)
    at MysqlDriver.Object.<anonymous>.MysqlDriver.createPool (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:891:16)
    at MysqlDriver.<anonymous> (C:\Users\emers\Documents\newschool-backend\src\driver\mysql\MysqlDriver.ts:344:36)
    at step (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\emers\Documents\newschool-backend\node_modules\tslib\tslib.js:122:57)
```

**Comment by DavideCarvalho** [comment]
Banco de teste caiu a algum tempo. Como agora tem o gitpod e o docker compose top, bota pra apontar localmente algo assim

**Comment by DavideCarvalho** [comment]
O banco de teste tinha alguns problemas, principalmente se mais de uma pessoa rodasse os testes, então não quero fazer isso de novo

**Comment by felinto-dev** [comment]
> Banco de teste caiu a algum tempo. Como agora tem o gitpod e o docker compose top, bota pra apontar localmente algo assim

Adicionar suporte pra usar o banco de dados do docker compose ou gitpod está nos meus planos, eu só não fiz isso ainda porque eu tenho que ver se para rodar o projeto precisa de algum tipo de seed e qual seria a melhor forma de fazer isso.
